Add patch info to list cmd
dfetch-org/dfetch pull request #201
Opened 2021-07-20 18:54 UTC by jgeudens

This PR adds the patch info to the metadata so it can be shown  by the list command. This was logged as #198.

I have added a dedicated feature test, because otherwise it would make an existing test more complex.

2021-07-20 21:34 UTC, ben-edna approved these changes
Looks good!

2021-07-21 05:58 UTC, jgeudens commented
Thanks,

There is a pylint warning about which I'm not sure how to fix.

2021-07-21 10:18 UTC, ben-edna commented
> Thanks,
> 
> There is a pylint warning about which I'm not sure how to fix.

Maybe if we replace self._tag, self._branch and self._revision with a self._version of type Version, this gives enough room for the new self._patch?

2021-07-22 14:40 UTC, ben-edna requested changes

2021-07-22 14:40 UTC, ben-edna commented on dfetch/project/metadata.py
> +        """Applied patch as stored in the metadata.."""
```suggestion
        """The applied patch as stored in the metadata."""
```

2021-07-22 14:40 UTC, ben-edna commented on dfetch/project/metadata.py
> +        """Applied patch as stored in the metadata.."""
This fixes the codacy issue (I guess)

2021-07-22 15:54 UTC, jgeudens commented
Pylint warning has been fixed.

2021-07-22 16:46 UTC, jgeudens commented on dfetch/project/metadata.py
> +        """Applied patch as stored in the metadata.."""
Applied

2021-07-30 14:35 UTC, merged